---
title: "Publications"
subtitle: "List of publications"
---

## Peer-reviewed 

1. Khalil, I., Islam, M. R., Promi, S. A., Joy, A. D., Sayed, M. A., Acharjee, D., Al-Shammari, A. S., Rahman, M. T., Abrar, S., Bin Jamil, T.-S., Taseen, M., Biswas, S., **Mifty, S. K.**, Al-Badri, S. G., Debnath, A., Hossain, M. I., & Akter, M. M. (2026). Comparative effectiveness of cholesteryl ester transfer protein (CETP) inhibitors on cardiovascular outcomes: A comprehensive Bayesian network meta-analysis and network meta-regression. Medicine, 105(20), e48627. <https://doi.org/10.1097/MD.0000000000048627>

2. S. I. Chowdhury, **S. K. Mifty**, T. A. R. Khan, et al., “ Tolosa–Hunt Syndrome Presenting as Painful Unilateral Ophthalmoplegia in a 65-Year-Old Woman: A Case Report,” Clinical Case Reports 14, no. 2 (2026): e72012, <https://doi.org/10.1002/ccr3.72012>

3. **S. K. Mifty**, S. I. Chowdhury, T. Rahman, et al., “ A Forgotten Foe Returns: The Diagnostic Odyssey of Kala-Azar Masquerading as Myelodysplastic Syndrome in a Post-Elimination Era,” Clinical Case Reports 13, no. 11 (2025): e71402, <https://doi.org/10.1002/ccr3.71402>

4. Chowdhury, S. I., Taj, F. Y., Esha, S. N., **Mifty, S. K.**, & Khalil, I. (2025). Challenging diagnosis of adult-onset still’s disease (AOSD) in a young male: a case report highlighting the importance of early recognition and management. Annals of Medicine & Surgery, 87(10), 6712–6718. <https://doi.org/10.1097/MS9.0000000000003752>

5. Khalil, I., Islam, M.R., Promi, S.A., Joy, A.D., Sayed, M.A., Acharjee, D., Al-shammari, A.S., Abrar, S., Jamil, T.-S.B., Taseen, M., Biswas, S., **Mifty, S.K.**, Al-Badri, S.G., Debnath, A., Hossain, M.I. and Akter, M. (2025), Comparative Effectiveness of Cholesteryl Ester Transfer Protein (CETP) Inhibitors on Lipid Profiles in Adults With Hyperlipidemia: A Comprehensive Systematic Review and Frequentist Network Meta-Analysis of Randomized Controlled Trials. Clinical Cardiology, 48: e70204. <https://doi.org/10.1002/clc.70204>

## Under Review



## Conference 

### Poster Presentations


### Oral Presentations

